language: python

python: "3.6"

install:
  - pip install tox
  - pip install tox-travis

env:
  - TEST_DIR=mercury-common
  - TEST_DIR=mercury-inventory
  - TEST_DIR=mercury-log
  - TEST_DIR=mercury-rpc

script: cd src/$TEST_DIR && tox 

